<?php
$request = $block->getRequest();

$errorValue = $request->getParam('erro');
?>

<html>

<head>
    <title>Finalização</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style media="screen">
        /* Estilos CSS */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            text-align: center;
            background-color: #292929;
        }

        h1 {
            color: #333;
        }

        .failure h1 {
            color: #f37021;
        }

        .failure p {
            color: white;
        }

        .button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #333;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
            margin-top: 20px;
            border: 1px solid #f37021;
        }

        .cardMsg {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        .payment-success {
            text-align: center;
            font-family: Arial, sans-serif;
            color: #333333;
            margin-top: -200px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        .payment-success img,
        .card img {
            width: 250px;
            margin-bottom: 100px;
        }

        .payment-success h1 {
            font-size: 2.2rem;
            margin-bottom: 20px;
            color: #f37021;
        }

        .payment-success p {
            font-size: 1.4rem;
            margin-bottom: 30px;
            color: white;
        }

        .spinner {
            display: inline-block;
            width: 40px;
            height: 40px;
            border: 4px solid #f37021;
            border-radius: 50%;
            border-top-color: transparent;
            animation: spin 0.8s ease-in-out infinite;
        }

        .fade-out {
            animation-name: fadeOut;
            animation-duration: 0.5s;
            animation-fill-mode: forwards;
        }

        .fade-in {
            animation-name: fadeIn;
            animation-duration: 0.5s;
            animation-fill-mode: forwards;
        }

        @keyframes spin {
            0% {
                transform: rotate(0deg);
            }

            100% {
                transform: rotate(360deg);
            }
        }

        @keyframes fadeOut {
            0% {
                opacity: 1;
            }

            100% {
                opacity: 0;
            }
        }

        @keyframes fadeIn {
            0% {
                opacity: 0;
            }

            100% {
                opacity: 1;
            }
        }

        @media screen and (max-width: 768px) {
            .payment-success h1 {
                font-size: 1.3rem;
            }

            .payment-success p {
                font-size: 1.1rem;
            }

            .payment-success img {
                width: 250px;
            }
        }
    </style>

</head>

<body>
    <?php if ($errorValue != null) : ?>
        <div class="card failure">
            <img src="https://sejaefi.com.br/_ipx/_/images/components/footer/brand-efi-by-gn-v.svg" alt="">
            <h1>Falha ao processar pagamento!</h1>
            <p><?= $block->escapeHtml($errorValue) ?></p>
            <a href="/sales/order/history/" class="button">Voltar para pedidos</a>
        </div>
    <?php endif; ?>
    <?php if ($errorValue == null) : ?>
        <div class="payment-success">
            <img src="https://sejaefi.com.br/_ipx/_/images/components/footer/brand-efi-by-gn-v.svg" alt="">
            <h1>Pagamento Em Processamento!</h1>
            <p>Olá! O seu pagamento está sendo processado. Por favor, aguarde alguns segundos enquanto realizamos o processamento.</p>
            <div class="spinner"></div>
        </div>
    <?php endif; ?>
    <!-- JavaScript -->

    <script>
        let validatePayment = 0;

        let container = document.getElementsByClassName("payment-success")[0];

        let intervalId = setInterval(function() {
            fetch("/gerencianet/ajax/ofpaymentstatusajaxhandler?identificadorPagamento=<?= $block->escapeJs($block->escapeUrl($block->getData('identificadorPagamento'))) ?>", {
                    headers: {
                        'X-Requested-With': 'XMLHttpRequest'
                    }
                })
                .then(function(response) {

                    if (response.ok) {

                        return response.json();
                    }
                    throw new Error('Erro na resposta da requisição.');
                })
                .then(function(ofStatus) {
                    if (ofStatus.paid) {
                        container.classList.add("fade-out");
                        document.getElementsByClassName("spinner")[0].style.display = "none";

                        setTimeout(function() {
                            container.getElementsByTagName("h1")[0].innerText = "Pagamento processado com sucesso!";
                            container.getElementsByTagName("p")[0].innerText = "Você será redirecionado para o seu pedido em alguns instantes.";

                            container.classList.add("fade-in");
                        }, 500);

                        setTimeout(function() {
                            window.location.href = `/sales/order/view/order_id/${ofStatus.order_id}/`;
                        }, 5000);

                    }
                    if (validatePayment == 60) {

                        let link = document.createElement('a');
                        link.href = `/sales/order/view/order_id/${ofStatus.order_id}/`;
                        link.className = 'button';
                        link.innerText = 'Voltar para a fatura';
                        clearInterval(intervalId);
                        container.classList.add("fade-out");
                        document.getElementsByClassName("spinner")[0].style.display = "none";

                        setTimeout(function() {
                            container.getElementsByTagName("h1")[0].innerText = "Pagamento Não Processado";
                            container.getElementsByTagName("p")[0].innerText = "O tempo para processamento do pagamento expirou. Por favor, verifique sua fatura e o banco utilizado para pagamento";
                            container.appendChild(link);
                            container.classList.add("fade-in");
                        }, 500);
                    }
                    validatePayment++;
                })
                .catch(function(error) {
                    console.error(error);
                });
        }, 1000);
    </script>
</body>

</html>